services:
  mw:
    build:
      context: ./mw
    ports:
      - "8083:8083"
    environment:
      ERPNEXT_BASE_URL: http://host.docker.internal:8080
      APP_DEFAULTS_ENABLED: "true"
      APP_DEFAULTS_VENDOR_EMAIL: vendor@example.com
      APP_DEFAULTS_VENDOR_NAME: Vendor User
      APP_DEFAULTS_VENDOR_PASSWORD: VendorAAS!2026
      APP_DEFAULTS_VENDOR_SUPPLIER: Vendor A
      APP_DEFAULTS_SHOP_EMAIL: shop@example.com
      APP_DEFAULTS_SHOP_NAME: Shop User
      APP_DEFAULTS_SHOP_PASSWORD: ShopAAS!2026
      APP_DEFAULTS_SHOP_CUSTOMER: Shop A
      APP_DEFAULTS_HELPER_EMAIL: helper@example.com
      APP_DEFAULTS_HELPER_NAME: Helper User
      APP_DEFAULTS_HELPER_PASSWORD: HelperAAS!2026
    extra_hosts:
      - "host.docker.internal:host-gateway"
